### ISSUE TITLE
Try out the github collaboration flow

### ISSUE THREAD

**Issue by michael-dean-haynie** [michael-dean-haynie/haynie-game#2]
The purpose of this ticket is to get familiar with how to collaborate with other developers on github.
Since the flow is the objective, the actual code changes will be very simple.

**Acceptance Criteria**
* The border of the `#canvas` element should be 2 pixels instead of 1

**Collaboration Flow**
* Here in this ticket, under the "Development" section, create a new branch for this ticket.
* Go to this repository in github and copy the url from the big green "Code" button.
* Use that url  to clone this repository onto your own machine.
  * For example: `git clone <paste the url here>`
* On your machine, in the newly cloned repository you will checkout the branch that we created for this ticket specifically.
* Then you make changes to satisfy the acceptance criteria above ^^.
* You commit your changes, you push your commit(s).
  * For example `git push` (should work by default. uses the currently checked out branch)
* Then you come back to github and open a pull request.
  * Github will probably suggest it to you, but if not you can manually create a pull request to merge your branch for this ticket which has your code changes, into the `develop` branch.
* Then Dean will get notified of this PR and can review it, and then merge it. And then the ticket will close.

**Comment by bilalpirzada** [comment]
Can I do this? if yes, assign it to me

**Comment by michael-dean-haynie** [comment]
Hey @bilalpirzada - thank you for the pr (#6)!
It's perfect and I would merge it, but since it was an exercise intended specifically for @phaynie I'm going to let them do it.

I assume you found this repo because I tagged the issue as a "good first issue". That's my bad, I didn't realize it would advertise itself.

If you are interested in the project I'll be fleshing out some more open ended tickets in the near future.

**Comment by michael-dean-haynie** [comment]
@phaynie FYI i updated the default branch to be `develop` instead of `main`.
This shouldn't change anything for your flow - just letting you know in case you notice the difference.
